minor_changes:
- assible-test - Remove em dash from the Pytest configuration file in order to
  be readable on systems where preferred encoding is ASCII.
  (https://github.com/assible/assible/issues/71739)
