---

- name: Network Getting Started First Playbook
  connection: assible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Get config for VyOS devices
      vyos.vyos.vyos_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ assible_net_hostname }} and the OS is {{ assible_net_version }}"
